version: '3.9'
services:
  #---
  queue-message-rabbitmq:
    container_name: queue-message-rabbitmq
    restart: always
    networks:
      - mcr-srv-practice.infra.net
  #---
  ordering-db-azure-edge:
    container_name: ordering-db-azure-edge
    restart: always
    environment:
      MSSQL_SA_PASSWORD: Password123
      ACCEPT_EULA: Y
    volumes:
      - ordering-db-data:/var/opt/mssql
    networks:
      - mcr-srv-practice.infra.net
  #---
  ordering-api:
    container_name: ordering-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - queue-message-rabbitmq
      - ordering-db-azure-edge
    networks:
      - mcr-srv-practice.service.net
      - mcr-srv-practice.infra.net
    ports:
      - "5004:80"
    restart: always