version: '3.9'
services:
  ##---
  basket-db-redis:
    image: redis:alpine
  #---
  basket-api:
    image: ${DOCKER_REGISTRY-}basket-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ../../
      dockerfile: docker/basket-api/Dockerfile
  #---
  queue-message-rabbitmq:
    image: rabbitmq:3-management-alpine

#network section
networks:
  #---
  mcr-srv-practice.service.net:
    name: mcr-srv-practice.service.net
    driver: bridge
  #---
  mcr-srv-practice.infra.net:
    name: mcr-srv-practice.infra.net
    driver: bridge

  #volumes section